import SwiftUI

// Auto-generated by Last Mile - do not edit manually
enum AppConfig {
    static let primaryColor    = Color(hex: "#8B5CF6")
    static let accentColor     = Color(hex: "#3B82F6")
    static let backgroundColor = Color(hex: "#FFFFFF")
    static let fontDesign: Font.Design = .rounded
    static let preferredColorScheme: ColorScheme? = nil
    static let ownerName       = "اسمك هنا"
    static let ownerTitle      = "مطور iOS"
    static let ownerBio        = "أطور تطبيقات iOS جميلة وسريعة الأداء"
    static let avatarEmoji     = "👨‍💻"
    static let skills          = ["SwiftUI", "Xcode", "Git", "Figma", "REST API"]
    static let projects: [(name: String, emoji: String)] = [
        ("تطبيق متجر",  "🛍️"),
        ("تطبيق صحة",   "💪"),
        ("تطبيق تعليم", "📚"),
    ]
}
